### ISSUE TITLE
Add todo 

### ISSUE THREAD

**Issue by zurda** [fac-15/AwesomeTodo#2]
- [x] Clone object + push original 
- [x] Return new array with new todo 
- [x] Add id to every new todo 
- [x] Leave input argument unchanged
